version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq_c
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # HTTP management UI
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass
    restart: always
    networks:
      - casestudy


  # DATABASES ---------------------------------POSTGRES
  micropsql:
    container_name: micropsql_c
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reportingservice
      - POSTGRES_USER=psqlusername
      - POSTGRES_PASSWORD=psqlpassword
    volumes:
      - micropsql_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - casestudy


  # CLOUD NATIVE MESSAGING SYSTEM -------NATS

  nats:
    image: nats:2.9-alpine
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
    entrypoint: ["nats-server", "-p", "4222", "-m", "8222", "--jetstream"]
    tty: true
    networks:
      - casestudy


networks:
  casestudy:
    driver: bridge
      
volumes:
  micropsql_db_data: {}
