version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq_c
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # HTTP management UI
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass
    restart: always

