
const AppService = {
  AUTHENTICATION: "AUTHENTICATION",
  BIDDING: "BIDDING",
  INVOICE: "INVOICE",
  ROOM: "ROOM",
  NOTIFICATION:"NOTIFICATION",
  REPORTING: "REPORTING",
};

module.exports = AppService;
